/// The sounds the app plays (#98): each a bundled 44.1 kHz mono 16-bit WAV
/// generated by `tools/sfx.py`, recorded in `assets/audio/LICENSES.md`.
/// `test/guards/audio_assets_test.dart` derives "the clips the app plays"
/// from this list; #101 plays them.
library;

enum Clip { deal, flip, snap, chime, music }

class ClipSpec {
  const ClipSpec(this.asset, {required this.loop});

  /// The asset path, as `pubspec.yaml` declares it.
  final String asset;

  /// A background bed that repeats seamlessly, rather than a one-shot.
  final bool loop;
}

const Map<Clip, ClipSpec> clips = {
  Clip.deal: ClipSpec('assets/audio/deal.wav', loop: false),
  Clip.flip: ClipSpec('assets/audio/flip.wav', loop: false),
  Clip.snap: ClipSpec('assets/audio/snap.wav', loop: false),
  Clip.chime: ClipSpec('assets/audio/chime.wav', loop: false),
  Clip.music: ClipSpec('assets/audio/music.wav', loop: true),
};
